<!-- Js Plugins -->
<script src="{{ Asset('js/jquery-3.3.1.min.js') }}"></script>
<script src="{{ Asset('js/bootstrap.min.js') }}"></script>
<script src="{{ Asset('js/jquery.nice-select.min.js') }}"></script>
<script src="{{ Asset('js/jquery-ui.min.js') }}"></script>
<script src="{{ Asset('js/jquery.slicknav.js') }}"></script>
<script src="{{ Asset('js/mixitup.min.js') }}"></script>
<script src="{{ Asset('js/owl.carousel.min.js') }}"></script>
<script src="{{ Asset('js/main.js') }}"></script>
